import helmet from '@fastify/helmet';
import { ValidationPipe, VersioningType } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import hbs from 'handlebars';
import { join, resolve } from 'path';
import { AppModule } from './app.module';
import { MyLogger } from './services/log/log.service';

function setVersioning(app: NestFastifyApplication) {
  app.enableVersioning({
    type: VersioningType.URI,
  });
}

function setValidation(app: NestFastifyApplication) {
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transformOptions: {
        enableImplicitConversion: true,
        exposeUnsetFields: false,
      },
    }),
  );
}

function setSwagger(app: NestFastifyApplication) {
  // https://docs.nestjs.com/openapi/introduction
  const config = new DocumentBuilder()
    .setTitle('Demo API Documentation')
    .setDescription(
      'This documentation is generated by <a href="https://docs.nestjs.com/openapi/introduction" target="_blank">@nestjs/swagger</a>.',
    )
    .addServer(process.env.STAGE_PATH || '')
    .addBearerAuth({
      // https://docs.nestjs.com/openapi/security#bearer-authentication
      type: 'http',
      description: 'Please enter your accessToken',
    })
    .setVersion('0.0.0')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  // https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
  SwaggerModule.setup('/docs', app, document, {
    // customfavIcon: 'https://avatars0.githubusercontent.com/u/7658037?v=3&s=200',
    // customJs: [
    //   'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.1/swagger-ui-bundle.min.js',
    //   'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.1/swagger-ui-standalone-preset.min.js',
    // ],
    // customCssUrl: ['https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.1/swagger-ui.min.css'],
  });
}

function setHBS(app: NestFastifyApplication) {
  const dir = resolve();
  app.useStaticAssets({
    root: [join(dir, 'public'), join(dir, 'node_modules', 'swagger-ui-dist')],
    prefix: '/public/',
  });
  app.setViewEngine({
    engine: {
      handlebars: hbs,
    },
    templates: join(dir, 'views'),
  });
}

export async function createApp() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter(), {
    cors: true,
    logger: false,
  });
  app.useLogger(app.get(MyLogger));

  await app.register(helmet, { contentSecurityPolicy: false });

  setHBS(app);
  setVersioning(app);
  setValidation(app);
  setSwagger(app);
  return app;
}
